name: Run tests

on: [push]

jobs:
  run_tests_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Unzip library
        working-directory: ./scripts/run_tests
        run: |
          unzip lib.zip

      - name: Run tests
        working-directory: ./scripts/run_tests
        run: |
          ./run_tests.sh